version: "2"
run:
  build-tags:
    - integ
    - integfuzz
linters:
  default: none
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*\.pb\.go
      - .*\.gen\.go
      - genfiles$
      - vendor$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(istio.io/)
    goimports:
      local-prefixes:
        - istio.io/
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go
      - .*\.gen\.go
      - genfiles$
      - vendor$
      - third_party$
      - builtin$
      - examples$
