version: "2"
run:
  build-tags:
    - integ
    - integfuzz
linters:
  default: none
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go$|tests/|samples/
      - linters:
          - staticcheck
        text: 'SA1019: package github.com/golang/protobuf/jsonpb'
      - linters:
          - staticcheck
        text: 'SA1019: "github.com/golang/protobuf/jsonpb"'
      - linters:
          - staticcheck
        text: 'SA1019: grpc.Dial is deprecated: use NewClient instead'
      - linters:
          - staticcheck
        text: 'SA1019: grpc.DialContext is deprecated: use NewClient instead'
      - linters:
          - staticcheck
        text: 'SA1019: grpc.WithBlock is deprecated'
      - linters:
          - staticcheck
        text: 'SA1019: grpc.FailOnNonTempDialError'
      - linters:
          - staticcheck
        text: 'SA1019: grpc.WithReturnConnectionError'
    paths:
      - .*\.pb\.go
      - .*\.gen\.go
      - genfiles$
      - vendor$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(istio.io/)
    goimports:
      local-prefixes:
        - istio.io/
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go
      - .*\.gen\.go
      - genfiles$
      - vendor$
      - third_party$
      - builtin$
      - examples$
